title: Byungjin Jun
author: Byungjin Jun
email: bjun@kma.ac.kr
description: >-
  Byungjin Jun is a professor of Computer Science at Korea Military Academy.
  His research spans computer networks, network security, web performance and QoE,
  and mission-critical networked systems.
baseurl: ""
url: "https://byungjinjun.github.io"
linkedin_username: byungjin-jun-47691b83
github_username: ByungjinJun

markdown: kramdown
plugins:
  - jekyll-seo-tag

disqus:
  shortname: jin55
